---

- name: Host Conf
  hosts: orarac-hosts
  user: vagrant
  become: yes
  roles:
    - common
    - oracle_host
    - oracle_host_storage

- name: GI Install And ASM Conf
  hosts: orarac-hosts
  user: vagrant
  become: yes
  roles:
    - oracle_gi_install
    - oracle_asm_conf

- name: Oracle Database Install And Database create
  hosts: orarac-hosts
  user: vagrant
  become: yes
  roles:
    - oracle_db_install
    - oracle_db_create
