---

- name: Install EPEL Repo
  yum:
    name: "{{ epel_rpm }}"
    state: installed
  when: configure_epel_repo and ansible_os_family == "RedHat"
  tags: epelrepo

- name: Get newest OL Repo
  get_url:
    dest: "{{ repo_dir }}/{{ ol_repo_file }}"
    url: "http://public-yum.oracle.com/{{ ol_repo_file }}"
    backup: yes
  when: configure_public_yum_repo and ansible_distribution == "OracleLinux"
  tags: olrepo

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ common_packages }}"
  when: install_os_packages and ansible_os_family == "RedHat"
  tags: common_packages

- name: Start and enable NTP
  service:
    name: ntpd
    state: started
    enabled: yes
  when: configure_ntp
  tags: ntp

- name: Add motd
  template:
    src: motd.j2
    dest: /etc/motd
  when: configure_motd
  tags: motd
