---

- name: User add group
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ oracle_groups }}"
  tags:
    - group

- name: User add oracle user
  user:
    name: "{{ item.username }}"
    group: "{{ item.primary_group }}"
    groups: "{{ item.other_groups }}"
    uid: "{{ item.uid }}"
    generate_ssh_key: yes
    append: yes
    state: present
    password: "{{ item.passwd }}"
  with_items: "{{ oracle_users }}"
  tags:
    - user

- name: User add grid user
  user:
    name: "{{ item.username }}"
    group: "{{ item.primary_group }}"
    groups: "{{ item.other_groups }}"
    uid: "{{ item.uid }}"
    generate_ssh_key: yes
    append: yes
    state: present
    password: "{{ item.passwd }}"
  with_items: "{{ grid_users }}"

- name: Add oracle User to sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/"{{ item.username }}"
    owner: root
    mode: 0600
  with_items: "{{ oracle_users }}"
  when: configure_oracle_sudo
  tags:
    - sudoers

- name: Add grid User to sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/"{{ item.username }}"
    owner: root
    mode: 0600
  with_items: "{{ grid_users }}"
  when: role_separation and configure_oracle_sudo
  tags:
    - sudoers
